# Generated by Django 4.1.7 on 2023-04-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='name',
            field=models.CharField(default='firstname secondname', max_length=30),
            preserve_default=False,
        ),
    ]
