# Generated by Django 4.1.7 on 2023-04-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userextended_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextended',
            name='role',
        ),
        migrations.AddField(
            model_name='userextended',
            name='isStudent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
