# Generated by Django 4.1.7 on 2023-04-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userextended_role_userextended_isstudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='isStudent',
            field=models.BooleanField(),
        ),
    ]
