# Generated by Django 4.1.7 on 2023-04-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
